version: 1
disable_existing_loggers: false
root:
  level: DEBUG
  handlers: [console]
handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    filters: [httpx]
formatters:
  detailed:
    format: "%(asctime)s | %(levelname)s (%(name)s) | %(filename)s:%(funcName)s:%(lineno)d - %(message)s"
filters:
  httpx:
    name: httpx
